services:
  api:
    container_name: scrapestar__api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  ui:
    container_name: scrapestar__ui
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
  mongodb:
    container_name: scrapestar__mongodb
    image: mongo
    volumes:
      - ./:/app
    ports:
      - "27017:27017"
