name: CI master api
on:
  push:
    paths:
      - 'api/**'
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./api

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install npm packages
        run: npm install

      - name: Build
        run: npm run build

      # - name: Run unit tests
      #   run: npm run test
